use std::fs;

use crate::interpreter::Globals;

const MCMETA: &str = r#"
{
    "pack": {
        "pack_format": 3,
        "description": "Datapack generated by the Emerald Programming Language"
    }
}
"#;


pub fn generate_datapack(globals: &Globals) {

    fs::remove_dir_all("emeraldgen").unwrap();
    fs::create_dir_all("emeraldgen/data/mrld/functions").unwrap();
    fs::write("emeraldgen/pack.mcmeta", MCMETA).unwrap();

    for (i, v) in &globals.mcfuncs.map {
        fs::write(format!("emeraldgen/data/mrld/functions/gen{}.mcfunction", i), v.join("\n")).unwrap();
    }

}

